/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'calculator': RouteRecordInfo<'calculator', '/calculator', Record<never, never>, Record<never, never>>,
    'calculator-results': RouteRecordInfo<'calculator-results', '/calculator/results', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'finances-debts': RouteRecordInfo<'finances-debts', '/finances/debts', Record<never, never>, Record<never, never>>,
    'finances-expenses': RouteRecordInfo<'finances-expenses', '/finances/expenses', Record<never, never>, Record<never, never>>,
    'finances-investments': RouteRecordInfo<'finances-investments', '/finances/investments', Record<never, never>, Record<never, never>>,
    'finances-profile': RouteRecordInfo<'finances-profile', '/finances/profile', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'gap-analysis': RouteRecordInfo<'gap-analysis', '/gap-analysis', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'onboarding': RouteRecordInfo<'onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    'privacy': RouteRecordInfo<'privacy', '/privacy', Record<never, never>, Record<never, never>>,
    'progress': RouteRecordInfo<'progress', '/progress', Record<never, never>, Record<never, never>>,
    'recommendations': RouteRecordInfo<'recommendations', '/recommendations', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'resources': RouteRecordInfo<'resources', '/resources', Record<never, never>, Record<never, never>>,
    'scenarios': RouteRecordInfo<'scenarios', '/scenarios', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'terms': RouteRecordInfo<'terms', '/terms', Record<never, never>, Record<never, never>>,
  }
}
